### ISSUE TITLE
Parser replaces wrong part of username, wich screws up the text

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/mentions#22]
Report:
when I type "here we go @jamil" and enabled "Replace Mentions in Text:" then its converted to code like see http://pastebin.com/65U1r49y

> here we go @#FF0000;" class="username-coloured">jamil

Reported here: https://www.phpbb.com/community/viewtopic.php?p=13983851#p13983851

**Comment by Wolfsblvt** [comment]
Seems to be some issue with the replace positions.

**Comment by ppdcom** [comment]
Let me know how I can help in testing for this issue

**Comment by ppdcom** [comment]
Hi Wolfsblvt, 

I was doing some testing and its seems that its some other plugin that is creating issues. Conflicting plugin is 

https://github.com/bruninoit/hashtag

I was testing some color, bold and glow bbcodes and they are also output the code in post instead of results. but after disabling them all works fine. Sorry for this issue

**Comment by Wolfsblvt** [comment]
So the other extension is causing the error, do I get it right?
If this is the fact, can I close this issue then?

**Comment by ppdcom** [comment]
Yes please close the issue and continue developing your awesome module... looking forward to see its stable release. Once again Thank You
